param(
    [ValidateSet('Inspect', 'Build', 'PlayLevel', 'ImportArt', 'Capture', 'Validate', 'Open', 'Play')]
    [string]$Action = 'Build',
    [string]$ProjectRoot = 'D:\UE\Projects\StarJourney',
    [string]$EngineRoot = 'D:\UE\UE_5.8',
    [string]$VaultRoot = 'D:\UE\VaultCache\FlyingSc0fe89709cde4V1\data'
)
$ErrorActionPreference = 'Stop'
$SourceRoot = Join-Path $PSScriptRoot 'StarJourney'
$ProjectFile = Join-Path $ProjectRoot 'StarJourney.uproject'
$Marker = Join-Path $ProjectRoot '.starjourney-managed'
$Editor = Join-Path $EngineRoot 'Engine\Binaries\Win64\UnrealEditor.exe'
$Commandlet = Join-Path $EngineRoot 'Engine\Binaries\Win64\UnrealEditor-Cmd.exe'
if (!(Test-Path $Editor)) { throw "Unreal Editor not found: $Editor" }
if ((Test-Path $ProjectRoot) -and !(Test-Path $Marker)) {
    throw "Existing unmanaged directory; choose a new ProjectRoot: $ProjectRoot"
}
New-Item $ProjectRoot -ItemType Directory -Force | Out-Null
Set-Content $Marker 'Generated by night/unreal/Manage-StarJourney.ps1' -Encoding UTF8
Copy-Item (Join-Path $SourceRoot 'StarJourney.uproject') $ProjectFile -Force
foreach ($Launcher in @('Open-Editor.cmd', 'Play-Demo.cmd')) {
    Copy-Item (Join-Path $SourceRoot $Launcher) $ProjectRoot -Force
}
foreach ($Folder in @('Config', 'Content')) {
    Copy-Item (Join-Path $SourceRoot $Folder) $ProjectRoot -Recurse -Force
}
$Assets = Join-Path $ProjectRoot 'Content\LP_sci_fi_island'
if (!(Test-Path $Assets)) {
    $VaultAssets = Join-Path $VaultRoot 'Content\LP_sci_fi_island'
    if (!(Test-Path $VaultAssets)) { throw "Asset source not found: $VaultAssets" }
    Copy-Item $VaultAssets (Join-Path $ProjectRoot 'Content') -Recurse
}
$Logs = Join-Path $ProjectRoot 'Saved\Logs'
New-Item $Logs -ItemType Directory -Force | Out-Null
if ($Action -eq 'Open') {
    Start-Process $Editor -ArgumentList @('"' + $ProjectFile + '"', '-NoSplash', '-NoVSync')
    Write-Output "Opened $ProjectFile"
    exit 0
}
if ($Action -eq 'Play') {
    Start-Process $Editor -ArgumentList @('"' + $ProjectFile + '"', '-game', '-windowed', '-ResX=1600', '-ResY=900', '-NoSplash')
    Write-Output "Playing $ProjectFile"
    exit 0
}
if ($Action -eq 'ImportArt') {
    # The Blender export lives in the source repository, outside the work project,
    # and the shared copy step above only mirrors Config and Content. Stage art/
    # into the project so import_art.py finds <ProjectRoot>\art\export without
    # needing STAR_ART_EXPORT. Contents are merged, never deleted, so a manual
    # drop into the project's art\export survives.
    $ArtSource = Join-Path $PSScriptRoot '..\art'
    if (Test-Path $ArtSource) {
        $ArtTarget = Join-Path $ProjectRoot 'art'
        New-Item $ArtTarget -ItemType Directory -Force | Out-Null
        Copy-Item (Join-Path $ArtSource '*') $ArtTarget -Recurse -Force
    } else {
        Write-Warning "No art source at $ArtSource; import_art.py will use an existing project copy or STAR_ART_EXPORT."
    }
}
$RunStarted = Get-Date
if ($Action -in @('Capture', 'Validate')) {
    $ScriptName = if ($Action -eq 'Capture') { 'capture_scene.py' } else { 'validate_play.py' }
    $Script = Join-Path $ProjectRoot "Content\Python\$ScriptName"
    $Process = Start-Process $Editor -Wait -PassThru -ArgumentList @('"' + $ProjectFile + '"', '-unattended', '-NoSplash', '-NoSound', '-RenderOffscreen', '-windowed', '-ResX=1600', '-ResY=900', '"-ExecutePythonScript=' + $Script + '"', '"-abslog=' + $Logs + '\' + $Action + '.log"')
} else {
    $ScriptName = if ($Action -eq 'Inspect') { 'inspect_assets.py' } elseif ($Action -eq 'PlayLevel') { 'build_play_level.py' } elseif ($Action -eq 'ImportArt') { 'import_art.py' } else { 'build_scene.py' }
    $Script = Join-Path $ProjectRoot "Content\Python\$ScriptName"
    if ($Action -eq 'Build' -and (Test-Path (Join-Path $ProjectRoot 'Content\StarJourney'))) {
        $Backup = Join-Path $ProjectRoot ('Saved\SceneBackups\' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
        New-Item $Backup -ItemType Directory -Force | Out-Null
        Copy-Item (Join-Path $ProjectRoot 'Content\StarJourney') $Backup -Recurse
    }
    $Process = Start-Process $Commandlet -Wait -PassThru -NoNewWindow -ArgumentList @('"' + $ProjectFile + '"', '-run=pythonscript', '"-script=' + $Script + '"', '-unattended', '-NoSplash', '-NoSound', '-NullRHI', '"-abslog=' + $Logs + '\' + $Action + '.log"')
}
if ($Process.ExitCode -ne 0) { throw "UE $Action failed with exit code $($Process.ExitCode). See $Logs." }
if ($Action -in @('Capture', 'Validate')) {
    $ReportName = if ($Action -eq 'Capture') { 'capture_report.json' } else { 'play_report.json' }
    $ReportPath = Join-Path $ProjectRoot "Saved\SceneReports\$ReportName"
    if (!(Test-Path $ReportPath) -or (Get-Item $ReportPath).LastWriteTime -lt $RunStarted) {
        throw "UE $Action did not write a fresh report: $ReportPath"
    }
    $Report = Get-Content $ReportPath -Raw | ConvertFrom-Json
    if ($Report.error) { throw $Report.error }
    if (Select-String -Path (Join-Path $Logs "$Action.log") -Pattern 'Failed to compile Material|LogPython: Error:' -Quiet) {
        throw "UE $Action contains material/Python errors. See $Logs."
    }
}
if ($Action -eq 'PlayLevel') {
    $ReportPath = Join-Path $ProjectRoot 'Saved\SceneReports\play_level_report.json'
    if (!(Test-Path $ReportPath) -or (Get-Item $ReportPath).LastWriteTime -lt $RunStarted) {
        throw "UE PlayLevel did not write a fresh report: $ReportPath"
    }
    $Report = Get-Content $ReportPath -Raw | ConvertFrom-Json
    # A silently unset GameMode override is the failure that matters here: the
    # playable map would spawn no runner, and worse, the movie map would inherit
    # the gameplay mode and spawn one over the demo. Both are hard failures.
    if (!$Report.play_gamemode_set) { throw "UE PlayLevel could not set the playable map's game mode. See $ReportPath" }
    if (!$Report.cinematic_gamemode_set) { throw "UE PlayLevel could not pin the cinematic map to GameModeBase; the demo would inherit the gameplay mode. See $ReportPath" }
    if ($Report.warnings -and @($Report.warnings).Count -gt 0) { Write-Warning (@($Report.warnings) -join '; ') }
}
if ($Action -eq 'ImportArt') {
    $ReportPath = Join-Path $ProjectRoot 'Saved\SceneReports\import_art_report.json'
    if (!(Test-Path $ReportPath) -or (Get-Item $ReportPath).LastWriteTime -lt $RunStarted) {
        throw "UE ImportArt did not write a fresh report: $ReportPath"
    }
    $Report = Get-Content $ReportPath -Raw | ConvertFrom-Json
    # The unit assertion is the whole point of the import: a 100x scale mistake is
    # invisible everywhere else and silently poisons every later measurement, so a
    # failed assertion is a hard failure here.
    if (!$Report.scale_assertion_passed) {
        $Failed = @($Report.assets | Where-Object { !$_.height_ok } | ForEach-Object { $_.mesh })
        throw "UE ImportArt scale assertion failed for: $($Failed -join ', '). Check the Blender export scale. See $ReportPath"
    }
    if ($Report.warnings -and @($Report.warnings).Count -gt 0) { Write-Warning (@($Report.warnings) -join '; ') }
}
Write-Output "UE $Action completed: $ProjectFile"
