param(
    [ValidateSet('Inspect', 'Build', 'Capture', 'Validate', 'Open', 'Play')]
    [string]$Action = 'Build',
    [string]$ProjectRoot = 'D:\UE\Projects\StarJourney',
    [string]$EngineRoot = 'D:\UE\UE_5.8',
    [string]$VaultRoot = 'D:\UE\VaultCache\FlyingSc0fe89709cde4V1\data'
)
$ErrorActionPreference = 'Stop'
$SourceRoot = Join-Path $PSScriptRoot 'StarJourney'
$ProjectFile = Join-Path $ProjectRoot 'StarJourney.uproject'
$Marker = Join-Path $ProjectRoot '.starjourney-managed'
$Editor = Join-Path $EngineRoot 'Engine\Binaries\Win64\UnrealEditor.exe'
$Commandlet = Join-Path $EngineRoot 'Engine\Binaries\Win64\UnrealEditor-Cmd.exe'
if (!(Test-Path $Editor)) { throw "Unreal Editor not found: $Editor" }
if ((Test-Path $ProjectRoot) -and !(Test-Path $Marker)) {
    throw "Existing unmanaged directory; choose a new ProjectRoot: $ProjectRoot"
}
New-Item $ProjectRoot -ItemType Directory -Force | Out-Null
Set-Content $Marker 'Generated by night/unreal/Manage-StarJourney.ps1' -Encoding UTF8
Copy-Item (Join-Path $SourceRoot 'StarJourney.uproject') $ProjectFile -Force
foreach ($Launcher in @('Open-Editor.cmd', 'Play-Demo.cmd')) {
    Copy-Item (Join-Path $SourceRoot $Launcher) $ProjectRoot -Force
}
foreach ($Folder in @('Config', 'Content')) {
    Copy-Item (Join-Path $SourceRoot $Folder) $ProjectRoot -Recurse -Force
}
$Assets = Join-Path $ProjectRoot 'Content\LP_sci_fi_island'
if (!(Test-Path $Assets)) {
    $VaultAssets = Join-Path $VaultRoot 'Content\LP_sci_fi_island'
    if (!(Test-Path $VaultAssets)) { throw "Asset source not found: $VaultAssets" }
    Copy-Item $VaultAssets (Join-Path $ProjectRoot 'Content') -Recurse
}
$Logs = Join-Path $ProjectRoot 'Saved\Logs'
New-Item $Logs -ItemType Directory -Force | Out-Null
if ($Action -eq 'Open') {
    Start-Process $Editor -ArgumentList @('"' + $ProjectFile + '"', '-NoSplash', '-NoVSync')
    Write-Output "Opened $ProjectFile"
    exit 0
}
if ($Action -eq 'Play') {
    Start-Process $Editor -ArgumentList @('"' + $ProjectFile + '"', '-game', '-windowed', '-ResX=1600', '-ResY=900', '-NoSplash')
    Write-Output "Playing $ProjectFile"
    exit 0
}
$RunStarted = Get-Date
if ($Action -in @('Capture', 'Validate')) {
    $ScriptName = if ($Action -eq 'Capture') { 'capture_scene.py' } else { 'validate_play.py' }
    $Script = Join-Path $ProjectRoot "Content\Python\$ScriptName"
    $Process = Start-Process $Editor -Wait -PassThru -ArgumentList @('"' + $ProjectFile + '"', '-unattended', '-NoSplash', '-NoSound', '-RenderOffscreen', '-windowed', '-ResX=1600', '-ResY=900', '"-ExecutePythonScript=' + $Script + '"', '"-abslog=' + $Logs + '\' + $Action + '.log"')
} else {
    $ScriptName = if ($Action -eq 'Inspect') { 'inspect_assets.py' } else { 'build_scene.py' }
    $Script = Join-Path $ProjectRoot "Content\Python\$ScriptName"
    if ($Action -eq 'Build' -and (Test-Path (Join-Path $ProjectRoot 'Content\StarJourney'))) {
        $Backup = Join-Path $ProjectRoot ('Saved\SceneBackups\' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
        New-Item $Backup -ItemType Directory -Force | Out-Null
        Copy-Item (Join-Path $ProjectRoot 'Content\StarJourney') $Backup -Recurse
    }
    $Process = Start-Process $Commandlet -Wait -PassThru -NoNewWindow -ArgumentList @('"' + $ProjectFile + '"', '-run=pythonscript', '"-script=' + $Script + '"', '-unattended', '-NoSplash', '-NoSound', '-NullRHI', '"-abslog=' + $Logs + '\' + $Action + '.log"')
}
if ($Process.ExitCode -ne 0) { throw "UE $Action failed with exit code $($Process.ExitCode). See $Logs." }
if ($Action -in @('Capture', 'Validate')) {
    $ReportName = if ($Action -eq 'Capture') { 'capture_report.json' } else { 'play_report.json' }
    $ReportPath = Join-Path $ProjectRoot "Saved\SceneReports\$ReportName"
    if (!(Test-Path $ReportPath) -or (Get-Item $ReportPath).LastWriteTime -lt $RunStarted) {
        throw "UE $Action did not write a fresh report: $ReportPath"
    }
    $Report = Get-Content $ReportPath -Raw | ConvertFrom-Json
    if ($Report.error) { throw $Report.error }
    if (Select-String -Path (Join-Path $Logs "$Action.log") -Pattern 'Failed to compile Material|LogPython: Error:' -Quiet) {
        throw "UE $Action contains material/Python errors. See $Logs."
    }
}
Write-Output "UE $Action completed: $ProjectFile"
